version: '3.1'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      - '8080:8080'
    environment:
      - DOCKER_ENV=1
