version: '3.1'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
