# fly.toml app configuration file generated for caho on 2023-10-28T20:06:01-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "caho"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024