### Ping

GET {{baseUrl}}/ping

### Sign In

POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "username": "Sn0wye",
  "password": "12345678"
}

### Get Profile
GET {{baseUrl}}/auth/profile
