export const clerkStyles = {
  rootBox: 'w-full',
  card: 'bg-white text-zinc-950 rounded-none shadow-none dark:bg-zinc-950 dark:text-zinc-50 p-0 w-auto max-w-none m-0 after:p-px after:h-8 after:w-full clerk:after:w-8 clerk:after:h-full after:bg-white after:dark:bg-zinc-950 after:absolute after:left-0 after:bottom-0 after:translate-y-full clerk:after:translate-y-0 clerk:after:-translate-x-full clerk:after:top-0',
  headerTitle: 'text-2xl font-medium text-zinc-900 dark:text-zinc-50',
  headerSubtitle: 'text-sm text-zinc-500 dark:text-zinc-400',
  dividerLine: 'bg-zinc-200 dark:bg-zinc-900',
  dividerText: 'text-sm text-zinc-400 dark:text-zinc-500 font-normal',
  formFieldLabelRow: 'mb-2',
  formFieldLabel: 'text-sm peer-disabled:cursor-not-allowed peer-disabled:opacity-70 text-zinc-700 dark:text-zinc-300',
  formFieldInput: 'flex h-10 w-full rounded-md border border-zinc-200 bg-white px-3 py-2 text-sm shadow-sm ring-offset-white transition-colors placeholder:text-zinc-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 dark:border-zinc-900 dark:bg-zinc-900/10 dark:ring-offset-zinc-950 dark:placeholder:text-zinc-400 dark:focus-visible:ring-zinc-800',
  formButtonPrimary: 'tracking-normal h-10 px-4 py-2 bg-zinc-900 text-zinc-50 hover:bg-zinc-900/90 dark:bg-zinc-50 dark:text-zinc-900 dark:hover:bg-zinc-50/90 inline-flex rounded-md items-center justify-center text-sm font-medium ring-offset-white transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 dark:ring-offset-zinc-950 dark:focus-visible:ring-zinc-800 normal-case',
  socialButtonsIconButton: 'border border-zinc-200 dark:border-zinc-900 bg-white dark:bg-zinc-900/10 hover:bg-zinc-100 dark:hover:bg-zinc-900/80 h-10 rounded-md px-3 flex items-center justify-center font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50',
  socialButtonsProviderIcon: 'contrast-0 grayscale',
  footerActionText: 'text-zinc-500 dark:text-zinc-400',
  footerActionLink: 'text-zinc-900 dark:text-zinc-50 hover:text-zinc-900/80 dark:hover:text-zinc-50/80',
  formFieldWarningText: 'text-xs',
  formFieldSuccessText: 'text-xs',
  identityPreviewEditButtonIcon: 'text-zinc-700 dark:text-zinc-300',
  formResendCodeLink: 'text-zinc-500 dark:text-zinc-400',
  otpCodeFieldInput: 'focus:border-zinc-200 dark:focus:border-zinc-900',
  organizationSwitcherTrigger: 'border border-zinc-200 dark:border-zinc-900',
}