name: Deploy Docker Compose

on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose.yml'
  workflow_dispatch:

jobs:
  deploy-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml"
          target: "."

      - name: Restart services with new compose file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            echo "Validating docker-compose.yml..."
            docker compose config --quiet
            
            echo "Restarting services with new configuration..."
            docker compose up -d
            
            echo "Cleaning up old images..."
            docker image prune -f